$(document).ready(function(){
    $('.sidenav').sidenav({
        edge:'right'
    });
    $('.slider').slider({
            indicators:false,
            height:600
    });
     $('select').formSelect();
});
